$axure.loadCurrentPage({
  "url":"消息设置.html",
  "generationDate":new Date(1396321033436.78),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"8eecfef7f895461a9768c7335e0457b0",
    "type":"Axure:Page",
    "name":"消息设置",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f9c50d1204254a6dbb422a9d1c9cf1b4",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"2cb7ecbfe90b4a40b5469b989f9838cb"},
{
          "id":"2d496f42366444a780a5968491b8dff0",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"23e0087bd7374c8194aeadae2a56b8a3"},
{
          "id":"676bb6c93f4d49b4a12e3b9562a5a791",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"b23ee50ff3c1421baf9312d369720ae8"},
{
          "id":"af24f470d81c4dbfb8e46b053521eeec",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":175,
              "y":329},
            "size":{
              "width":705,
              "height":117}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d49661de777244f29fa60a6785204e95",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":175,
                  "y":329},
                "size":{
                  "width":705,
                  "height":117}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消息设置/u82.png"}},
{
          "id":"15509212180e4df084b984ade59341fe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":204,
              "y":323},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79d8fa2d6f3146dd80ab1188dbef421b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":204,
                  "y":323},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人主页/u174.png"}},
{
          "id":"eac64f6c8c1b4475baedc210b54e5529",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":349},
            "size":{
              "width":190,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7b64f0435ac4b43bb07f89577383f86",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":349},
                "size":{
                  "width":190,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"7f86f31733414f47a177404d7268f96f",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":401},
            "size":{
              "width":160,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db2c90bcdc5d4110a69af296bb37440b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":401},
                "size":{
                  "width":160,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"e5ec4c4bdac14fa4a84b80608a90d500",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":175,
              "y":462},
            "size":{
              "width":705,
              "height":168}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fefaadbd3f4f4aa1b351d9d8d8acf2c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":175,
                  "y":462},
                "size":{
                  "width":705,
                  "height":168}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消息设置/u90.png"}},
{
          "id":"c35852451a484a0b984cdee295f9aeb1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":204,
              "y":456},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f1a4860fee04e9681c80152a1ee03f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":204,
                  "y":456},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消息设置/u92.png"}},
{
          "id":"f41b7a1c1ede4160aa9a9a093b4865c4",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":481},
            "size":{
              "width":150,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e4e8f415f6f43d89966646bb0610e2f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":481},
                "size":{
                  "width":150,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"496630f5da84413496d8ff3d61ba2a0a",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":505},
            "size":{
              "width":160,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b97236d87604aa79c3c1aba2def31d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":505},
                "size":{
                  "width":160,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"d830365e4e5049709257ae260155a915",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":530},
            "size":{
              "width":160,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d523c493e13a4f46b84f41682cba1619",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":530},
                "size":{
                  "width":160,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"c4bd599a602241ebb739a4a84b68f787",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":375},
            "size":{
              "width":160,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c9849a685794c46965558f60c0e031d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":375},
                "size":{
                  "width":160,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"ddf72b3678db4d20894321c496c62b36",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":560},
            "size":{
              "width":160,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48309223619a484eb8c7e987ef664019",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":560},
                "size":{
                  "width":160,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"daf5800fd86f493892bb609bed1b64b7",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":586},
            "size":{
              "width":160,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dfcc29aa2fbd48d49acce8ff0c266a30",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":586},
                "size":{
                  "width":160,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"42f025e88b9b4d189381eb8b2b686975",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":427},
            "size":{
              "width":160,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91df70660c4946ce80218078b7cc666e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":427},
                "size":{
                  "width":160,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"7819d2f4cd5f4e00aeab8e92cf076136",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":611},
            "size":{
              "width":160,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"032c0b1b7d9d479eb6fe8d7fb9578ae6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":611},
                "size":{
                  "width":160,
                  "height":16}},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
    "2cb7ecbfe90b4a40b5469b989f9838cb":{
      "packageId":"2cb7ecbfe90b4a40b5469b989f9838cb",
      "type":"Axure:Master",
      "name":"设置页面",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"7a4d862ad1574c8d87c0871772404612",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "location":{
                "x":160,
                "y":312},
              "size":{
                "width":10,
                "height":1158}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/消息页面/u72_line.png"}},
{
            "id":"d89c69965cb64dbd89a886cdd50f18da",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "location":{
                "x":58,
                "y":314},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"420ac75c69024b7988476c369f32da54",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"16px",
                  "location":{
                    "x":58,
                    "y":314},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 设置",
                        "target":{
                          "targetType":"page",
                          "url":"设置.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"e682f78870524f3bb0c20b8203341d05",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "opacity":"0.2",
              "location":{
                "x":0,
                "y":333},
              "size":{
                "width":160,
                "height":10}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/消息页面/u75_line.png"}},
{
            "id":"adea30c55ec5499e9427bbb160669154",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "location":{
                "x":55,
                "y":353},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2369afccdabf40b598baaf02f0517c4f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"16px",
                  "location":{
                    "x":55,
                    "y":353},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 消息设置",
                        "target":{
                          "targetType":"page",
                          "url":"消息设置.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"b2ba183087ef47feb5f9c435e239d229",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "opacity":"0.2",
              "location":{
                "x":0,
                "y":372},
              "size":{
                "width":160,
                "height":10}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/消息页面/u75_line.png"}},
{
            "id":"1af46986ebfd4d7a9719db85f2c93096",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "location":{
                "x":55,
                "y":392},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cfc97b4993a543459f947f77d15428a6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"16px",
                  "location":{
                    "x":55,
                    "y":392},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 权限设置",
                        "target":{
                          "targetType":"page",
                          "url":"权限设置.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"8c9f48d2660c47919c2733830eb26216",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "opacity":"0.2",
              "location":{
                "x":0,
                "y":411},
              "size":{
                "width":160,
                "height":10}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/消息页面/u75_line.png"}}]}},
    "23e0087bd7374c8194aeadae2a56b8a3":{
      "packageId":"23e0087bd7374c8194aeadae2a56b8a3",
      "type":"Axure:Master",
      "name":"个人主页模板",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"0069c62041534978a44e316bd08ee30c",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":-20,
                "y":122},
              "size":{
                "width":910,
                "height":180}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0f6582ab0f364866967093b1bf970c84",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":-20,
                    "y":122},
                  "size":{
                    "width":910,
                    "height":180}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/个人主页/u177.png"}},
{
            "id":"a08acf9b829b4b9198cf7a6c4636aa6f",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":14,
                "y":122},
              "size":{
                "width":185,
                "height":177}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b4b85a4728604672a1db9eddc0f085f4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":14,
                    "y":122},
                  "size":{
                    "width":185,
                    "height":177}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/个人主页/u179.png"}},
{
            "id":"cbe9fe16d22f4863923843d868e88504",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Negreta', 'Arial'",
              "fontSize":"18px",
              "fontWeight":"700",
              "location":{
                "x":202,
                "y":145},
              "size":{
                "width":163,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fce0fadd8b344cf2aac17492295176c8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Negreta', 'Arial'",
                  "fontSize":"18px",
                  "fontWeight":"700",
                  "location":{
                    "x":202,
                    "y":145},
                  "size":{
                    "width":163,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"2e8858e2bcea4539a9055949e246a2e4",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":383,
                "y":150},
              "size":{
                "width":172,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5775e75e5c4344df9ab75da7df8b9250",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":383,
                    "y":150},
                  "size":{
                    "width":172,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"42189fa15b6945df864c7b3a4c58dde5",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":205,
                "y":248},
              "size":{
                "width":78,
                "height":48}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5bf4945f33e74668999c9b04d48b1011",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":205,
                    "y":248},
                  "size":{
                    "width":78,
                    "height":48}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"43cd3aa63c874f8e9f24babd32797d79",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":206,
                "y":201},
              "size":{
                "width":196,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3a12029b356e42b590593164b2730e4f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":206,
                    "y":201},
                  "size":{
                    "width":196,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"17295bd1c89d496588eacd019e5c053f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":572,
                "y":275},
              "size":{
                "width":105,
                "height":27},
              "cornerRadiusTopLeft":"10"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a56bcd1fd38641f9ab7c949a40bce7c0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":572,
                    "y":275},
                  "size":{
                    "width":105,
                    "height":27},
                  "cornerRadiusTopLeft":"10"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 关注",
                        "target":{
                          "targetType":"page",
                          "url":"关注.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/个人主页/u189.png"}},
{
            "id":"c0710eecc8c44e6dba19e5e790b3c49c",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":677,
                "y":275},
              "size":{
                "width":105,
                "height":27},
              "cornerRadiusTopLeft":"10"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cda4545929544aa9bac7b8effa3e427f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":677,
                    "y":275},
                  "size":{
                    "width":105,
                    "height":27},
                  "cornerRadiusTopLeft":"10"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 被关注",
                        "target":{
                          "targetType":"page",
                          "url":"被关注.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/个人主页/u189.png"}},
{
            "id":"20ce35b367764b5d8297f85036502385",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":782,
                "y":275},
              "size":{
                "width":105,
                "height":27},
              "cornerRadiusTopLeft":"10"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"21421d267ef640438b0f48414488702d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":782,
                    "y":275},
                  "size":{
                    "width":105,
                    "height":27},
                  "cornerRadiusTopLeft":"10"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 收藏",
                        "target":{
                          "targetType":"page",
                          "url":"收藏.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/个人主页/u189.png"}},
{
            "id":"d842d7b214b84d2b996d967b637d28ca",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":278,
                "y":269},
              "size":{
                "width":82,
                "height":27}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a9554a46612d4069a0aebac8cc4abe92",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":278,
                    "y":269},
                  "size":{
                    "width":82,
                    "height":27}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/个人主页/u195.png"}},
{
            "id":"974d13f6d2bc41c3a6038b96c5ddf89d",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":278,
                "y":243},
              "size":{
                "width":82,
                "height":27}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"32d80bac4a754e7ba639b1f6fb332c34",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":278,
                    "y":243},
                  "size":{
                    "width":82,
                    "height":27}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/个人主页/u195.png"}},
{
            "id":"5c3abb71b8534f078c90fb406263187a",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":467,
                "y":275},
              "size":{
                "width":105,
                "height":27},
              "cornerRadiusTopLeft":"10"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0b87a62319284f2fb2df289e96a52632",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":467,
                    "y":275},
                  "size":{
                    "width":105,
                    "height":27},
                  "cornerRadiusTopLeft":"10"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 个人主页",
                        "target":{
                          "targetType":"page",
                          "url":"个人主页.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/个人主页/u189.png"}},
{
            "id":"d2055da0a2c846169be02bb235457fc0",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF0000FF,
                "opacity":1},
              "location":{
                "x":412,
                "y":201},
              "size":{
                "width":79,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"199bee3f27c54114846234c4b13b7fd5",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000FF,
                    "opacity":1},
                  "location":{
                    "x":412,
                    "y":201},
                  "size":{
                    "width":79,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 设置",
                        "target":{
                          "targetType":"page",
                          "url":"设置.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "annotation":{
              "描述":"如果是自己的主页，才显示这个按钮"},
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}},
    "b23ee50ff3c1421baf9312d369720ae8":{
      "packageId":"b23ee50ff3c1421baf9312d369720ae8",
      "type":"Axure:Master",
      "name":"总模板",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"0ae2793c7c89491a90c4256993c84c48",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":13,
                "y":12},
              "size":{
                "width":885,
                "height":100}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c08ccb54ffd5423c9ebe9b4e6df5b52d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":13,
                    "y":12},
                  "size":{
                    "width":885,
                    "height":100}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页/u1.png"}},
{
            "id":"0e72ddd93c0d4209abf5fbca86d609b8",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":21,
                "y":94},
              "size":{
                "width":250,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3c85c142b3da4b58919b285110734510",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":21,
                    "y":94},
                  "size":{
                    "width":250,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"196f861694d04727a53aaccf56d99625",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":277,
                "y":94},
              "size":{
                "width":35,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"bd8184e1a5834c8c8cd0b9e5c31f882b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":277,
                    "y":94},
                  "size":{
                    "width":35,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"0faea047a17a49b1bb602c32644067f3",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "location":{
                "x":430,
                "y":88},
              "size":{
                "width":109,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4c6a2756179a4d63b7cb22e598d5fa77",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "location":{
                    "x":430,
                    "y":88},
                  "size":{
                    "width":109,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 新窗口/标签页 打开 个人主页",
                        "target":{
                          "targetType":"page",
                          "url":"个人主页.html",
                          "includeVariables":true},
                        "linkType":"new"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"88cd95062e174d1481a23545100306b9",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "location":{
                "x":650,
                "y":104},
              "size":{
                "width":10,
                "height":1}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/首页/u9_line.png"}},
{
            "id":"972d4917835544e88096df20ce761078",
            "label":"",
            "type":"menuObject",
            "styleType":"menuObject",
            "visible":true,
            "style":{
              "location":{
                "x":560,
                "y":81},
              "size":{
                "width":200,
                "height":30},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5f5e17f29abc44ad89fa782d21e416db",
                "label":"",
                "type":"table",
                "styleType":"table",
                "visible":true,
                "style":{
                  "size":{
                    "width":200,
                    "height":30}},
                "adaptiveStyles":{
},
                "objects":[{
                    "id":"c82f3037925848349f3652502ebb76eb",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "size":{
                        "width":100,
                        "height":30}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"de1f3902a2494c4eb61726a5376d346b",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "size":{
                            "width":100,
                            "height":30}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/首页/u12.png"}},
{
                    "id":"da659e1ed52345da8f4609c599bbfe1b",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":100,
                        "y":0},
                      "size":{
                        "width":100,
                        "height":30}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"baaf17a6c94548bbb5f6126acd0c3596",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":100,
                            "y":0},
                          "size":{
                            "width":100,
                            "height":30}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/首页/u14.png"}}]},
{
                "id":"38e2bb66f3104c4f936933e98bd817ea",
                "label":"",
                "type":"menuObject",
                "styleType":"menuObject",
                "visible":true,
                "style":{
                  "location":{
                    "x":0,
                    "y":30},
                  "size":{
                    "width":100,
                    "height":120},
                  "limbo":false,
                  "borderWidth":"-1"},
                "adaptiveStyles":{
},
                "objects":[{
                    "id":"d8fd5162d2e544f5a5cff1979aa9badf",
                    "label":"",
                    "type":"table",
                    "styleType":"table",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":100,
                        "height":120}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"cb9a83da82d04a9fa410aa10a1d3dd42",
                        "label":"",
                        "type":"tableCell",
                        "styleType":"tableCell",
                        "visible":true,
                        "style":{
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "size":{
                            "width":100,
                            "height":20},
                          "limbo":false},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"da73de9c79434cccb41faa8c7410a322",
                            "label":"",
                            "isContained":true,
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "horizontalAlignment":"center",
                              "verticalAlignment":"middle",
                              "fill":{
                                "fillType":"solid",
                                "color":0xFFFFFF},
                              "size":{
                                "width":100,
                                "height":20},
                              "limbo":false},
                            "adaptiveStyles":{
}}],
                        "images":{
                          "normal~":"images/梦想广场/u26.png"}},
{
                        "id":"5205171681c74917a77f1472b84605c0",
                        "label":"",
                        "type":"tableCell",
                        "styleType":"tableCell",
                        "visible":true,
                        "style":{
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":0,
                            "y":40},
                          "size":{
                            "width":100,
                            "height":20},
                          "limbo":false},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"7892ecb5aeff4e7684fc2785c889eef4",
                            "label":"",
                            "isContained":true,
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "horizontalAlignment":"center",
                              "verticalAlignment":"middle",
                              "fill":{
                                "fillType":"solid",
                                "color":0xFFFFFF},
                              "location":{
                                "x":0,
                                "y":40},
                              "size":{
                                "width":100,
                                "height":20},
                              "limbo":false},
                            "adaptiveStyles":{
}}],
                        "images":{
                          "normal~":"images/梦想广场/u26.png"}},
{
                        "id":"2f4783fa3ed64b93861c41fea897163e",
                        "label":"",
                        "type":"tableCell",
                        "styleType":"tableCell",
                        "visible":true,
                        "style":{
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":0,
                            "y":60},
                          "size":{
                            "width":100,
                            "height":20},
                          "limbo":false},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"05a7c683c45143e3a9dba2442c68e63c",
                            "label":"",
                            "isContained":true,
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "horizontalAlignment":"center",
                              "verticalAlignment":"middle",
                              "fill":{
                                "fillType":"solid",
                                "color":0xFFFFFF},
                              "location":{
                                "x":0,
                                "y":60},
                              "size":{
                                "width":100,
                                "height":20},
                              "limbo":false},
                            "adaptiveStyles":{
}}],
                        "images":{
                          "normal~":"images/梦想广场/u26.png"}},
{
                        "id":"a0ebc702d57544498b1508e9fd5464c7",
                        "label":"",
                        "type":"tableCell",
                        "styleType":"tableCell",
                        "visible":true,
                        "style":{
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":0,
                            "y":80},
                          "size":{
                            "width":100,
                            "height":20},
                          "limbo":false},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"82acf1717c4d4e56963ac1217f7df6ae",
                            "label":"",
                            "isContained":true,
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "horizontalAlignment":"center",
                              "verticalAlignment":"middle",
                              "fill":{
                                "fillType":"solid",
                                "color":0xFFFFFF},
                              "location":{
                                "x":0,
                                "y":80},
                              "size":{
                                "width":100,
                                "height":20},
                              "limbo":false},
                            "adaptiveStyles":{
}}],
                        "images":{
                          "normal~":"images/梦想广场/u26.png"}},
{
                        "id":"c908c87c4a87400c8978428e583039a5",
                        "label":"",
                        "type":"tableCell",
                        "styleType":"tableCell",
                        "visible":true,
                        "style":{
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":0,
                            "y":20},
                          "size":{
                            "width":100,
                            "height":20},
                          "limbo":false},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"8b45f23126f24c75967f861b95ba70ce",
                            "label":"",
                            "isContained":true,
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "horizontalAlignment":"center",
                              "verticalAlignment":"middle",
                              "fill":{
                                "fillType":"solid",
                                "color":0xFFFFFF},
                              "location":{
                                "x":0,
                                "y":20},
                              "size":{
                                "width":100,
                                "height":20},
                              "limbo":false},
                            "adaptiveStyles":{
}}],
                        "images":{
                          "normal~":"images/梦想广场/u26.png"}},
{
                        "id":"dc5563ef6f194992a8a048b8758500fd",
                        "label":"",
                        "type":"tableCell",
                        "styleType":"tableCell",
                        "visible":true,
                        "style":{
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":0,
                            "y":100},
                          "size":{
                            "width":100,
                            "height":20},
                          "limbo":false},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"4488b887819d42a8b42ab3a862977700",
                            "label":"",
                            "isContained":true,
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "horizontalAlignment":"center",
                              "verticalAlignment":"middle",
                              "fill":{
                                "fillType":"solid",
                                "color":0xFFFFFF},
                              "location":{
                                "x":0,
                                "y":100},
                              "size":{
                                "width":100,
                                "height":20},
                              "limbo":false},
                            "adaptiveStyles":{
}}],
                        "images":{
                          "normal~":"images/梦想广场/u30.png"}}]}],
                "parentCellId":"c82f3037925848349f3652502ebb76eb"},
{
                "id":"8602aec3bb9a488c8e74b8ef62b28e36",
                "label":"",
                "type":"menuObject",
                "styleType":"menuObject",
                "visible":true,
                "style":{
                  "location":{
                    "x":100,
                    "y":30},
                  "size":{
                    "width":100,
                    "height":60},
                  "limbo":false,
                  "borderWidth":"-1"},
                "adaptiveStyles":{
},
                "objects":[{
                    "id":"99b1247886094d95b40f404171a78bfd",
                    "label":"",
                    "type":"table",
                    "styleType":"table",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":100,
                        "height":60}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"8ccdbbed68e2474d92aaeb41eeaed40f",
                        "label":"",
                        "type":"tableCell",
                        "styleType":"tableCell",
                        "visible":true,
                        "style":{
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "size":{
                            "width":100,
                            "height":20},
                          "limbo":false},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"9fa399c4b7c843a0a18096c3ed402881",
                            "label":"",
                            "isContained":true,
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "horizontalAlignment":"center",
                              "verticalAlignment":"middle",
                              "fill":{
                                "fillType":"solid",
                                "color":0xFFFFFF},
                              "size":{
                                "width":100,
                                "height":20},
                              "limbo":false},
                            "adaptiveStyles":{
}}],
                        "images":{
                          "normal~":"images/梦想广场/u26.png"}},
{
                        "id":"1be8d1810de147c9bccf867b33d175f2",
                        "label":"",
                        "type":"tableCell",
                        "styleType":"tableCell",
                        "visible":true,
                        "style":{
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":0,
                            "y":20},
                          "size":{
                            "width":100,
                            "height":20},
                          "limbo":false},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"862db9f783d64545b08661ec43fafcc5",
                            "label":"",
                            "isContained":true,
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "horizontalAlignment":"center",
                              "verticalAlignment":"middle",
                              "fill":{
                                "fillType":"solid",
                                "color":0xFFFFFF},
                              "location":{
                                "x":0,
                                "y":20},
                              "size":{
                                "width":100,
                                "height":20},
                              "limbo":false},
                            "adaptiveStyles":{
}}],
                        "images":{
                          "normal~":"images/梦想广场/u26.png"}},
{
                        "id":"f965746406f54b7991bb30fb248eb2ac",
                        "label":"",
                        "type":"tableCell",
                        "styleType":"tableCell",
                        "visible":true,
                        "style":{
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFFFF0000,
                            "opacity":1},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":0,
                            "y":40},
                          "size":{
                            "width":100,
                            "height":20},
                          "limbo":false},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"dd41e50f592a431389523bf8d05fbd7f",
                            "label":"",
                            "isContained":true,
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "horizontalAlignment":"center",
                              "verticalAlignment":"middle",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFFFF0000,
                                "opacity":1},
                              "fill":{
                                "fillType":"solid",
                                "color":0xFFFFFF},
                              "location":{
                                "x":0,
                                "y":40},
                              "size":{
                                "width":100,
                                "height":20},
                              "limbo":false},
                            "adaptiveStyles":{
}}],
                        "images":{
                          "normal~":"images/梦想广场/u30.png"}}]}],
                "parentCellId":"da659e1ed52345da8f4609c599bbfe1b"}]},
{
            "id":"46382d8fcea948c2a7623a555e603624",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":570,
                "y":89},
              "size":{
                "width":20,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e1d067f6f0a84465a336162bd3bebd76",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":570,
                    "y":89},
                  "size":{
                    "width":20,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页/u38.png"}},
{
            "id":"64691f45ddcc40259336c205c934c77b",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":670,
                "y":89},
              "size":{
                "width":18,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"76a1019a53d6412ca57634f280335fc5",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":670,
                    "y":89},
                  "size":{
                    "width":18,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页/u40.png"}},
{
            "id":"773d84276b264d148d2ea2de0e2c8fa8",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF0000FF,
                "opacity":1},
              "location":{
                "x":788,
                "y":89},
              "size":{
                "width":92,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0b099ec465bf4104bb67277bca21535a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000FF,
                    "opacity":1},
                  "location":{
                    "x":788,
                    "y":89},
                  "size":{
                    "width":92,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "f9c50d1204254a6dbb422a9d1c9cf1b4":{
      "scriptId":"u0",
      "7a4d862ad1574c8d87c0871772404612":{
        "scriptId":"u1"},
      "d89c69965cb64dbd89a886cdd50f18da":{
        "scriptId":"u2"},
      "420ac75c69024b7988476c369f32da54":{
        "scriptId":"u3"},
      "e682f78870524f3bb0c20b8203341d05":{
        "scriptId":"u4"},
      "adea30c55ec5499e9427bbb160669154":{
        "scriptId":"u5"},
      "2369afccdabf40b598baaf02f0517c4f":{
        "scriptId":"u6"},
      "b2ba183087ef47feb5f9c435e239d229":{
        "scriptId":"u7"},
      "1af46986ebfd4d7a9719db85f2c93096":{
        "scriptId":"u8"},
      "cfc97b4993a543459f947f77d15428a6":{
        "scriptId":"u9"},
      "8c9f48d2660c47919c2733830eb26216":{
        "scriptId":"u10"}},
    "2d496f42366444a780a5968491b8dff0":{
      "scriptId":"u11",
      "0069c62041534978a44e316bd08ee30c":{
        "scriptId":"u12"},
      "0f6582ab0f364866967093b1bf970c84":{
        "scriptId":"u13"},
      "a08acf9b829b4b9198cf7a6c4636aa6f":{
        "scriptId":"u14"},
      "b4b85a4728604672a1db9eddc0f085f4":{
        "scriptId":"u15"},
      "cbe9fe16d22f4863923843d868e88504":{
        "scriptId":"u16"},
      "fce0fadd8b344cf2aac17492295176c8":{
        "scriptId":"u17"},
      "2e8858e2bcea4539a9055949e246a2e4":{
        "scriptId":"u18"},
      "5775e75e5c4344df9ab75da7df8b9250":{
        "scriptId":"u19"},
      "42189fa15b6945df864c7b3a4c58dde5":{
        "scriptId":"u20"},
      "5bf4945f33e74668999c9b04d48b1011":{
        "scriptId":"u21"},
      "43cd3aa63c874f8e9f24babd32797d79":{
        "scriptId":"u22"},
      "3a12029b356e42b590593164b2730e4f":{
        "scriptId":"u23"},
      "17295bd1c89d496588eacd019e5c053f":{
        "scriptId":"u24"},
      "a56bcd1fd38641f9ab7c949a40bce7c0":{
        "scriptId":"u25"},
      "c0710eecc8c44e6dba19e5e790b3c49c":{
        "scriptId":"u26"},
      "cda4545929544aa9bac7b8effa3e427f":{
        "scriptId":"u27"},
      "20ce35b367764b5d8297f85036502385":{
        "scriptId":"u28"},
      "21421d267ef640438b0f48414488702d":{
        "scriptId":"u29"},
      "d842d7b214b84d2b996d967b637d28ca":{
        "scriptId":"u30"},
      "a9554a46612d4069a0aebac8cc4abe92":{
        "scriptId":"u31"},
      "974d13f6d2bc41c3a6038b96c5ddf89d":{
        "scriptId":"u32"},
      "32d80bac4a754e7ba639b1f6fb332c34":{
        "scriptId":"u33"},
      "5c3abb71b8534f078c90fb406263187a":{
        "scriptId":"u34"},
      "0b87a62319284f2fb2df289e96a52632":{
        "scriptId":"u35"},
      "d2055da0a2c846169be02bb235457fc0":{
        "scriptId":"u36"},
      "199bee3f27c54114846234c4b13b7fd5":{
        "scriptId":"u37"}},
    "676bb6c93f4d49b4a12e3b9562a5a791":{
      "scriptId":"u38",
      "0ae2793c7c89491a90c4256993c84c48":{
        "scriptId":"u39"},
      "c08ccb54ffd5423c9ebe9b4e6df5b52d":{
        "scriptId":"u40"},
      "0e72ddd93c0d4209abf5fbca86d609b8":{
        "scriptId":"u41"},
      "3c85c142b3da4b58919b285110734510":{
        "scriptId":"u42"},
      "196f861694d04727a53aaccf56d99625":{
        "scriptId":"u43"},
      "bd8184e1a5834c8c8cd0b9e5c31f882b":{
        "scriptId":"u44"},
      "0faea047a17a49b1bb602c32644067f3":{
        "scriptId":"u45"},
      "4c6a2756179a4d63b7cb22e598d5fa77":{
        "scriptId":"u46"},
      "88cd95062e174d1481a23545100306b9":{
        "scriptId":"u47"},
      "972d4917835544e88096df20ce761078":{
        "scriptId":"u48"},
      "5f5e17f29abc44ad89fa782d21e416db":{
        "scriptId":"u49"},
      "c82f3037925848349f3652502ebb76eb":{
        "scriptId":"u50"},
      "de1f3902a2494c4eb61726a5376d346b":{
        "scriptId":"u51"},
      "da659e1ed52345da8f4609c599bbfe1b":{
        "scriptId":"u52"},
      "baaf17a6c94548bbb5f6126acd0c3596":{
        "scriptId":"u53"},
      "38e2bb66f3104c4f936933e98bd817ea":{
        "scriptId":"u54"},
      "d8fd5162d2e544f5a5cff1979aa9badf":{
        "scriptId":"u55"},
      "cb9a83da82d04a9fa410aa10a1d3dd42":{
        "scriptId":"u56"},
      "da73de9c79434cccb41faa8c7410a322":{
        "scriptId":"u57"},
      "c908c87c4a87400c8978428e583039a5":{
        "scriptId":"u58"},
      "8b45f23126f24c75967f861b95ba70ce":{
        "scriptId":"u59"},
      "5205171681c74917a77f1472b84605c0":{
        "scriptId":"u60"},
      "7892ecb5aeff4e7684fc2785c889eef4":{
        "scriptId":"u61"},
      "2f4783fa3ed64b93861c41fea897163e":{
        "scriptId":"u62"},
      "05a7c683c45143e3a9dba2442c68e63c":{
        "scriptId":"u63"},
      "a0ebc702d57544498b1508e9fd5464c7":{
        "scriptId":"u64"},
      "82acf1717c4d4e56963ac1217f7df6ae":{
        "scriptId":"u65"},
      "dc5563ef6f194992a8a048b8758500fd":{
        "scriptId":"u66"},
      "4488b887819d42a8b42ab3a862977700":{
        "scriptId":"u67"},
      "8602aec3bb9a488c8e74b8ef62b28e36":{
        "scriptId":"u68"},
      "99b1247886094d95b40f404171a78bfd":{
        "scriptId":"u69"},
      "8ccdbbed68e2474d92aaeb41eeaed40f":{
        "scriptId":"u70"},
      "9fa399c4b7c843a0a18096c3ed402881":{
        "scriptId":"u71"},
      "1be8d1810de147c9bccf867b33d175f2":{
        "scriptId":"u72"},
      "862db9f783d64545b08661ec43fafcc5":{
        "scriptId":"u73"},
      "f965746406f54b7991bb30fb248eb2ac":{
        "scriptId":"u74"},
      "dd41e50f592a431389523bf8d05fbd7f":{
        "scriptId":"u75"},
      "46382d8fcea948c2a7623a555e603624":{
        "scriptId":"u76"},
      "e1d067f6f0a84465a336162bd3bebd76":{
        "scriptId":"u77"},
      "64691f45ddcc40259336c205c934c77b":{
        "scriptId":"u78"},
      "76a1019a53d6412ca57634f280335fc5":{
        "scriptId":"u79"},
      "773d84276b264d148d2ea2de0e2c8fa8":{
        "scriptId":"u80"},
      "0b099ec465bf4104bb67277bca21535a":{
        "scriptId":"u81"}},
    "af24f470d81c4dbfb8e46b053521eeec":{
      "scriptId":"u82"},
    "d49661de777244f29fa60a6785204e95":{
      "scriptId":"u83"},
    "15509212180e4df084b984ade59341fe":{
      "scriptId":"u84"},
    "79d8fa2d6f3146dd80ab1188dbef421b":{
      "scriptId":"u85"},
    "eac64f6c8c1b4475baedc210b54e5529":{
      "scriptId":"u86"},
    "e7b64f0435ac4b43bb07f89577383f86":{
      "scriptId":"u87"},
    "7f86f31733414f47a177404d7268f96f":{
      "scriptId":"u88"},
    "db2c90bcdc5d4110a69af296bb37440b":{
      "scriptId":"u89"},
    "e5ec4c4bdac14fa4a84b80608a90d500":{
      "scriptId":"u90"},
    "fefaadbd3f4f4aa1b351d9d8d8acf2c6":{
      "scriptId":"u91"},
    "c35852451a484a0b984cdee295f9aeb1":{
      "scriptId":"u92"},
    "4f1a4860fee04e9681c80152a1ee03f6":{
      "scriptId":"u93"},
    "f41b7a1c1ede4160aa9a9a093b4865c4":{
      "scriptId":"u94"},
    "5e4e8f415f6f43d89966646bb0610e2f":{
      "scriptId":"u95"},
    "496630f5da84413496d8ff3d61ba2a0a":{
      "scriptId":"u96"},
    "7b97236d87604aa79c3c1aba2def31d2":{
      "scriptId":"u97"},
    "d830365e4e5049709257ae260155a915":{
      "scriptId":"u98"},
    "d523c493e13a4f46b84f41682cba1619":{
      "scriptId":"u99"},
    "c4bd599a602241ebb739a4a84b68f787":{
      "scriptId":"u100"},
    "3c9849a685794c46965558f60c0e031d":{
      "scriptId":"u101"},
    "ddf72b3678db4d20894321c496c62b36":{
      "scriptId":"u102"},
    "48309223619a484eb8c7e987ef664019":{
      "scriptId":"u103"},
    "daf5800fd86f493892bb609bed1b64b7":{
      "scriptId":"u104"},
    "dfcc29aa2fbd48d49acce8ff0c266a30":{
      "scriptId":"u105"},
    "42f025e88b9b4d189381eb8b2b686975":{
      "scriptId":"u106"},
    "91df70660c4946ce80218078b7cc666e":{
      "scriptId":"u107"},
    "7819d2f4cd5f4e00aeab8e92cf076136":{
      "scriptId":"u108"},
    "032c0b1b7d9d479eb6fe8d7fb9578ae6":{
      "scriptId":"u109"}}});